#
# Ticketsystem Trivial Tickets
#
# Matriculation numbers: 3040018, 6694964, 3478222
# Lecture:               Programmieren II, INF16B
# Lecturer:              Herr Prof. Dr. Helmut Neemann
# Institute:             Duale Hochschule Baden-Württemberg Mosbach
#
# ---------------
# Travis build configuration
#

language: go

go:
  - "1.11"

os:
  - osx
  - linux
  - windows

before_install:
  - go get -t -v ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) -c -F api
  - bash <(curl -s https://codecov.io/bash) -c -F commandLine
  - bash <(curl -s https://codecov.io/bash) -c -F server
  - bash <(curl -s https://codecov.io/bash) -c -F utilites

