language: go

go:
    - "1.11"
os:
    - osx
    - linux
    - windows

before_script:
    - echo "Display all current connections and used ports on this machine:"
    - netstat -an
    - echo "Checking if port 4443 is used by any process:"
    - netstat -an | grep ":4443" || echo "No process with port 4443 found"

