## Trivial Tickets Ticketsystem
## Copyright (C) 2019 The Contributors
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##
## Ticketsystem Trivial Tickets
##
## Matriculation numbers: 3040018, 6694964, 3478222
## Lecture:               Programmieren II, INF16B
## Lecturer:              Herr Prof. Dr. Helmut Neemann
## Institute:             Duale Hochschule Baden-Württemberg Mosbach
##
## ---------------
## Travis Build Configuration of
## Jekyll Site
##
## See https://travis-ci.com/mortenterhart/trivial-tickets
## for the current build status.
##

---

language: ruby

dist: trusty

sudo: false

# Use the latest Ruby 2.6
rvm:
  - 2.6.1

# Include the gh-pages branch to the Travis build
branches:
  only:
    - gh-pages

# Upgrade the managed bundler version to 2.0.1
# and install the required gems from the Gemfile
# and verify that Jekyll was installed correctly.
install:
  - gem uninstall bundler
  - gem install bundler --version "2.0.1"
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec jekyll --version

# Check the sass files for syntax validity.
before_script:
  - bundle exec sass --check --trace --sourcemap=none --scss _sass/*.scss assets/css/*.scss &&
      echo "Sass is alright."

# Build the site, check YAML front matter of all
# deployed files and generate a Liquid rendering
# profile.
script:
  - bundle exec jekyll build --strict_front_matter --unpublished --profile --trace
