## Trivial Tickets Ticketsystem
## Copyright (C) 2019 The Contributors
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##
## Ticketsystem Trivial Tickets
##
## Matriculation numbers: 3040018, 6694964, 3478222
## Lecture:               Programmieren II, INF16B
## Lecturer:              Herr Prof. Dr. Helmut Neemann
## Institute:             Duale Hochschule Baden-Württemberg Mosbach
##
## ---------------
## Jekyll Configuration
##
## See https://mortenterhart.github.io/trivial-tickets for the
## deployed page with this configuration.
##

---

# Set the Jekyll theme for the Github
# Pages site
theme: jekyll-theme-architect

# Set a title and description for the project
title: "Trivial Tickets"
description: "Support ticket system in Go"

# Title for the Wiki pages
wiki_title: "Trivial Tickets Wiki"

# Set the associated project repository
repository: mortenterhart/trivial-tickets

# Show the download buttons
show_downloads: true

# Set the website language and default encoding
lang: en-US
encoding: utf-8

# Use kramdown as Markdown engine
markdown: kramdown

# Generate the sidebar table of contents only
# for headings between minHeader and maxHeader
toc:
  minHeader: 2
  maxHeader: 3

# Use bundled plugins from the Github Pages
# gem and the included liquid plugins from
# the _includes/ folder.
plugins:
  - jemoji          # Display emojis in Markdown
  - jekyll-toc      # Generate a table of contents

# Change the GitHub download URLs to bundle the
# project from branch master instead of gh-pages
github:
  zip_url: "https://github.com/mortenterhart/trivial-tickets/zipball/master"
  tar_url: "https://github.com/mortenterhart/trivial-tickets/tarball/master"

# Exclude all project and build files
exclude:
  - "*.go"
  - "*.sh"
  - "*.bat"
  - "*.json"
  - "*.yml"
  - "*.toml"
  - ssl/
  - www/
  - Gemfile
  - Gemfile.lock
